// Pediatrics Midterm Exam - Set C (MBBCh) - 120 MCQs
// Fields: id, topic, source (lecture PDF), difficulty (Easy | Medium | Hard | Advanced),
//         question, options {A,B,C,D}, answer (letter), explanation
const questionsData = [
  { id: 1, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "An infant is brought for a routine check-up. Physical examination shows that the posterior fontanel is completely closed, but the anterior fontanel is wide open. At what age does the posterior fontanel normally complete closure?",
    options: { A: "2 to 3 months (6–8 weeks)", B: "6 to 9 months", C: "12 to 15 months", D: "18 to 24 months" },
    answer: "A", explanation: "Posterior fontanel normally closes between 6–8 weeks (2 to 3 months) of age." },
  { id: 2, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "A mother brings her 9-month-old infant concerned about growth. On assessment, the infant can sit unsupported, pull to stand, and uses a crude pincer grasp. What is the expected gross motor milestone at 9 months?",
    options: { A: "Walking unsupported", B: "Sitting unsupported and pulling to stand", C: "Running smoothly", D: "Hopping on one foot" },
    answer: "B", explanation: "Sitting unsupported and pulling to stand are hallmark gross motor milestones at 9 months." },
  { id: 3, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "At what age is an infant expected to TRIPLE their birth weight under normal physiological growth conditions?",
    options: { A: "5 months", B: "12 months (1 year)", C: "2 years", D: "3 years" },
    answer: "B", explanation: "Birth weight normally triples by 12 months (1 year) of age." },
  { id: 4, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "A 2-year-old child's height is measured at 86 cm. What is the expected birth length of a full-term neonate?",
    options: { A: "35 cm", B: "50 cm", C: "65 cm", D: "75 cm" },
    answer: "B", explanation: "Expected average birth length of a full-term newborn is 50 cm." },
  { id: 5, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "Which of the following is considered a major cause of DELAYED motor development in young children?",
    options: { A: "Congenital hypothyroidism (Cretinism)", B: "Hypervitaminosis C", C: "Mild transient physiological jaundice", D: "Physiological anemia of infancy" },
    answer: "A", explanation: "Congenital hypothyroidism (Cretinism) causes severe developmental and motor delay." },
  { id: 6, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Medium",
    question: "In assessing head circumference in a term infant, what is the average monthly increase during the first 3 months of life?",
    options: { A: "0.5 cm / month", B: "2.0 cm / month", C: "4.0 cm / month", D: "6.0 cm / month" },
    answer: "B", explanation: "Head circumference increases by an average of 2 cm/month during months 1–3." },
  { id: 7, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "All of the following are recognized RED FLAGS in infant social and language development EXCEPT:",
    options: { A: "No social smile by 2 months", B: "No babbling by 9 months", C: "Inability to speak 50 words by 6 months", D: "No response to name by 12 months" },
    answer: "C", explanation: "Speaking 50 words is a 24-month milestone; expecting 50 words at 6 months is unrealistic." },
  { id: 8, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Medium",
    question: "In calculating adjusted (corrected) age for a premature infant born at 32 weeks gestation, how many weeks are subtracted from chronological age?",
    options: { A: "2 weeks", B: "4 weeks", C: "8 weeks", D: "12 weeks" },
    answer: "C", explanation: "Prematurity adjustment for 32 weeks gestation: 40 - 32 = 8 weeks subtracted." },
  { id: 9, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "What is the normal average number of primary (deciduous) teeth present in a fully erupted childhood set?",
    options: { A: "16", B: "20", C: "24", D: "32" },
    answer: "B", explanation: "Primary (deciduous) dentition consists of 20 total teeth." },
  { id: 10, topic: "Growth & Development", source: "Growth & Development.pdf", difficulty: "Easy",
    question: "At what age does a child typically achieve complete daytime bladder control?",
    options: { A: "12 months", B: "18 months", C: "2 to 3 years", D: "6 to 7 years" },
    answer: "C", explanation: "Daytime bladder control is achieved by 2 to 3 years of age." },

  { id: 11, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "What is the primary immunoglobulin found in highest concentration in human milk, protecting the infant gastrointestinal mucosal lining?",
    options: { A: "Secretory IgA", B: "Serum IgG", C: "Pentameric IgM", D: "Monomeric IgE" },
    answer: "A", explanation: "Secretory IgA is the predominant immunoglobulin coating mucosal surfaces in human milk." },
  { id: 12, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "The WHO/UNICEF 'Ten Steps to Successful Breastfeeding' under the Baby-Friendly Hospital Initiative (BFHI) explicitly prohibits:",
    options: { A: "Rooming-in 24 hours a day", B: "Giving artificial teats or pacifiers to breastfeeding infants", C: "On-demand feeding", D: "Antenatal breastfeeding education" },
    answer: "B", explanation: "Step 9 of BFHI prohibits artificial teats or pacifiers to prevent nipple confusion." },
  { id: 13, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Medium",
    question: "Breast milk jaundice (late-onset non-conjugated hyperbilirubinemia) typically peaks at what age in a healthy breastfed infant?",
    options: { A: "First 24 hours of life", B: "3 to 5 days of life", C: "2 to 3 weeks of life", D: "3 months of life" },
    answer: "C", explanation: "Breast milk jaundice peaks late, typically around 2 to 3 weeks of age." },
  { id: 14, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "In comparing mature human milk to cow's milk, human milk has a lower concentration of which major mineral, protecting immature infant kidneys?",
    options: { A: "Lactose", B: "Whey protein", C: "Sodium and protein (lower renal solute load)", D: "Polyunsaturated fatty acids" },
    answer: "C", explanation: "Low sodium and protein content in human milk provides a low renal solute load for infant kidneys." },
  { id: 15, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Medium",
    question: "An infant with severe cow's milk protein allergy (CMPA) who fails to improve on extensively hydrolyzed formula should be switched to:",
    options: { A: "Unmodified goat's milk", B: "Amino acid-based (elemental) formula", C: "Standard soy formula", D: "Anti-regurgitation starch formula" },
    answer: "B", explanation: "Severe CMPA failing extensively hydrolyzed formula requires an amino acid-based formula." },
  { id: 16, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "Which carbohydrate is added to Anti-Regurgitation (AR) infant formulas to thicken the liquid in the infant's stomach?",
    options: { A: "Sucrose", B: "Pre-gelatinized rice or corn starch", C: "Fructose", D: "Maltodextrin alone" },
    answer: "B", explanation: "Pre-gelatinized rice or corn starch is added to thicken Anti-Regurgitation (AR) formulas." },
  { id: 17, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "Maternal active infection with which of the following pathogens is an absolute contraindication to breastfeeding in developed guidelines?",
    options: { A: "Hepatitis C Virus without nipple cracking", B: "Human Immunodeficiency Virus (HIV)", C: "Cytomegalovirus (CMV) in term infant", D: "Treated Mastitis" },
    answer: "B", explanation: "Maternal HIV infection is an absolute contraindication to breastfeeding in global guidelines." },
  { id: 18, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "Foremilk is released at the beginning of a nursing session. Its main compositional feature is high:",
    options: { A: "Fat content", B: "Water and lactose content", C: "Caloric density (>100 kcal/oz)", D: "Casein precipitate" },
    answer: "B", explanation: "Foremilk released early in a feed is rich in water and lactose to quench thirst." },
  { id: 19, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "At what age should iron supplementation (1 mg/kg/day) be routinely initiated for an exclusively breastfed TERM infant to prevent iron depletion?",
    options: { A: "At birth", B: "At 4 to 6 months of age", C: "At 12 months of age", D: "At 24 months of age" },
    answer: "B", explanation: "Iron supplementation (1 mg/kg/day) is started at 4–6 months in exclusively breastfed term infants." },
  { id: 20, topic: "Infant Feeding", source: "infant feeding undergraduate.pdf", difficulty: "Easy",
    question: "Which hormone is directly responsible for contraction of myoepithelial cells in mammary alveoli, producing the milk ejection ('let-down') reflex?",
    options: { A: "Prolactin", B: "Oxytocin", C: "Progesterone", D: "Estrogen" },
    answer: "B", explanation: "Oxytocin contracts alveolar myoepithelial cells to mediate the milk let-down reflex." },

  { id: 21, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "According to WHO criteria, severe acute malnutrition (SAM) in children aged 6 to 59 months is diagnosed when Mid-Upper Arm Circumference (MUAC) is less than:",
    options: { A: "115 mm (11.5 cm)", B: "125 mm (12.5 cm)", C: "135 mm (13.5 cm)", D: "145 mm (14.5 cm)" },
    answer: "A", explanation: "MUAC < 115 mm (< 11.5 cm) defines Severe Acute Malnutrition (SAM) in children 6–59 months." },
  { id: 22, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "In the Wellcome classification of childhood malnutrition, a child presenting with Weight-for-Age < 60% of expected standard and WITHOUT edema is classified as having:",
    options: { A: "Underweight", B: "Marasmus", C: "Kwashiorkor", D: "Marasmic Kwashiorkor" },
    answer: "B", explanation: "Wellcome classification: Weight-for-Age < 60% without edema = Marasmus." },
  { id: 23, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "A 12-month-old child with SAM is admitted for treatment. During the stabilization phase, the starter therapeutic milk formula administered is:",
    options: { A: "F-50", B: "F-75", C: "F-100", D: "Full-cream cow's milk" },
    answer: "B", explanation: "Starter milk F-75 is used during the initial stabilization phase of SAM." },
  { id: 24, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "In SAM rehabilitation phase, catch-up growth formula F-100 provides how many kilocalories per 100 mL?",
    options: { A: "75 kcal", B: "100 kcal", C: "150 kcal", D: "200 kcal" },
    answer: "B", explanation: "Catch-up growth formula F-100 supplies 100 kcal / 100 mL during SAM rehabilitation." },
  { id: 25, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Medium",
    question: "ReSoMal (Rehydration Solution for Malnutrition) differs from standard WHO ORS by having:",
    options: { A: "Lower sodium and higher potassium/magnesium", B: "Higher sodium and lower potassium", C: "Zero glucose content", D: "Equal parts sodium and chloride" },
    answer: "A", explanation: "ReSoMal contains lower sodium (45 mmol/L) and higher potassium/magnesium than standard ORS." },
  { id: 26, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Medium",
    question: "What is the essential electrolyte imbalance responsible for life-threatening cardiac arrhythmias in Refeeding Syndrome?",
    options: { A: "Severe hypophosphatemia", B: "Severe hypercalcemia", C: "Hypernatremia", D: "Hypermagnesemia" },
    answer: "A", explanation: "Rapid refeeding causes intracellular uptake of phosphate, triggering severe hypophosphatemia." },
  { id: 27, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "A severely malnourished child presents with bilateral pitting edema of feet and legs, Moon face, apathy, and skin hyperpigmentation with peeling ('flaky paint' dermatosis). This clinical picture is diagnostic of:",
    options: { A: "Marasmus", B: "Kwashiorkor", C: "Scurvy", D: "Pellagra" },
    answer: "B", explanation: "Bilateral edema, Moon face, apathy, and flaky paint dermatosis pathognomonically define Kwashiorkor." },
  { id: 28, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Medium",
    question: "In a child with SAM, empirical broad-spectrum antibiotic coverage is recommended upon admission even if signs of infection are absent because:",
    options: { A: "Malnourished children fail to mount typical inflammatory signs (fever, leukocytosis)", B: "Antibiotics stimulate appetite directly", C: "Antibiotics prevent vitamin deficiencies", D: "SAM causes immediate kidney failure" },
    answer: "A", explanation: "SAM children lack typical infection signs (no fever/leukocytosis) due to immune suppression." },
  { id: 29, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Hard",
    question: "What is the single dose of oral Vitamin A given on Day 1 to an 8-month-old infant admitted with SAM (without corneal ulceration)?",
    options: { A: "50,000 IU", B: "100,000 IU", C: "200,000 IU", D: "500,000 IU" },
    answer: "B", explanation: "Infants aged 6–12 months with SAM receive 100,000 IU Vitamin A on Day 1." },
  { id: 30, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Easy",
    question: "Which vitamin deficiency causes Scurvy, presenting with painful swollen joints, pseudoparalysis, perifollicular hemorrhages, and bleeding gums?",
    options: { A: "Vitamin A", B: "Vitamin B1 (Thiamine)", C: "Vitamin C (Ascorbic acid)", D: "Vitamin D" },
    answer: "C", explanation: "Scurvy is caused by Vitamin C deficiency affecting collagen triple-helix formation." },

  { id: 31, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "Acute diarrhea is defined as the passage of 3 or more loose or watery stools per day lasting less than:",
    options: { A: "7 days", B: "14 days", C: "21 days", D: "30 days" },
    answer: "B", explanation: "Acute diarrhea is defined as loose/watery stools lasting less than 14 days." },
  { id: 32, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Medium",
    question: "A 10-month-old infant presents with acute watery diarrhea and vomiting. Exam shows sunken eyes, loss of skin turgor (skin pinch goes back slowly <2s), and eager drinking. What is the WHO hydration category?",
    options: { A: "No dehydration", B: "Some dehydration", C: "Severe dehydration", D: "Hypovolemic septic shock" },
    answer: "B", explanation: "Sunken eyes, skin pinch < 2s, and eager drinking classify as Some Dehydration under WHO rules." },
  { id: 33, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "What volume of ORS should be administered over 4 hours for a 10 kg child categorized as having 'Some Dehydration' under WHO Plan B?",
    options: { A: "200 to 300 mL", B: "500 to 1000 mL (50–100 mL/kg)", C: "1500 to 2000 mL", D: "2500 mL" },
    answer: "B", explanation: "WHO Plan B prescribes 50–100 mL/kg ORS over 4 hours (500–1000 mL for a 10 kg child)." },
  { id: 34, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Medium",
    question: "In WHO Plan C for Severe Dehydration in an infant UNDER 12 months, 100 mL/kg IV Ringer Lactate is given as:",
    options: { A: "30 mL/kg in 1 hour, then 70 mL/kg over 5 hours", B: "30 mL/kg in 30 minutes, then 70 mL/kg over 2.5 hours", C: "50 mL/kg in 1 hour, then 50 mL/kg in 1 hour", D: "100 mL/kg over 12 hours" },
    answer: "A", explanation: "Plan C IV fluid for infants < 12 months: 30 mL/kg in 1 hour, then 70 mL/kg over 5 hours." },
  { id: 35, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "Zinc supplementation given during acute diarrhea reduces duration and severity. What is the standard daily dose and duration for a child aged 18 months?",
    options: { A: "10 mg/day for 5 days", B: "20 mg/day for 10 to 14 days", C: "50 mg/day for 1 month", D: "100 mg single dose" },
    answer: "B", explanation: "Zinc dosage for children ≥ 6 months is 20 mg/day for 10 to 14 days." },
  { id: 36, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "Which pathogen causes bloody dysenteric diarrhea accompanied by high fever, tenesmus, and rectal prolapse in young children?",
    options: { A: "Rotavirus", B: "Enterotoxigenic E. coli (ETEC)", C: "Shigella dysenteriae", D: "Giardia lamblia" },
    answer: "C", explanation: "Shigella dysenteriae causes invasive dysentery with fever, tenesmus, and rectal prolapse." },
  { id: 37, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Medium",
    question: "Antibiotic treatment in Enterohemorrhagic E. coli (EHEC O157:H7) diarrhea is CONTRAINDICATED because it increases the risk of:",
    options: { A: "Hemolytic Uremic Syndrome (HUS)", B: "Toxic shock syndrome", C: "Hepatic encephalopathy", D: "Intussusception" },
    answer: "A", explanation: "Antibiotics in EHEC O157:H7 trigger Shiga toxin release, increasing risk of HUS." },
  { id: 38, topic: "Acute Diarrhea", source: "vomiting ,dirrhea.pdf", difficulty: "Medium",
    question: "Carbohydrate malabsorption (e.g., secondary lactose intolerance) following acute gastroenteritis is characterized by stool that is:",
    options: { A: "Greasy, bulky, and foul-smelling with neutral pH", B: "Watery, frothy, acidic (pH < 5.5) with positive reducing substances", C: "Grossly bloody with pus cells", D: "Rice-water pale without odor" },
    answer: "B", explanation: "Carbohydrate malabsorption produces frothy acidic stools (pH < 5.5) with positive reducing sugars." },
  { id: 39, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "Anti-motility agents (such as Loperamide) are strictly contraindicated in pediatric acute diarrhea because they can cause:",
    options: { A: "Paralytic ileus, toxic megacolon, and central nervous system depression", B: "Severe hypercalcemia", C: "Acute renal stone formation", D: "Anaphylactic airway obstruction" },
    answer: "A", explanation: "Loperamide causes paralytic ileus, toxic megacolon, and respiratory depression in young children." },
  { id: 40, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Easy",
    question: "Rotavirus vaccine is a live attenuated oral vaccine administered to infants in 2 or 3 doses starting at what age?",
    options: { A: "Birth", B: "2 months of age", C: "6 months of age", D: "12 months of age" },
    answer: "B", explanation: "Rotavirus oral vaccine schedule starts at 2 months of age." },

  { id: 41, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Easy",
    question: "What is the most sensitive early laboratory indicator of iron depletion before clinical anemia develops?",
    options: { A: "Decreased Hemoglobin level", B: "Decreased Mean Corpuscular Volume (MCV)", C: "Decreased Serum Ferritin", D: "Increased Hematocrit" },
    answer: "C", explanation: "Serum Ferritin is the most sensitive early marker reflecting depleted tissue iron stores." },
  { id: 42, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Easy",
    question: "In treating Iron Deficiency Anemia in a 15-month-old child, what is the recommended therapeutic dose of oral elemental iron?",
    options: { A: "1 mg/kg/day", B: "3 to 6 mg/kg/day divided in 2–3 doses", C: "15 mg/kg/day single bolus", D: "30 mg/kg/day" },
    answer: "B", explanation: "Therapeutic dose for Iron Deficiency Anemia is 3 to 6 mg/kg/day of elemental iron." },
  { id: 43, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Easy",
    question: "A 2-year-old child with pica (eating paint chips from old building walls) presents with irritability, constipation, microcytic anemia, and coarse basophilic stippling on peripheral blood film. What is the diagnosis?",
    options: { A: "Iron Deficiency Anemia", B: "Lead Poisoning (Plumbism)", C: "Beta-Thalassemia Major", D: "Glucose-6-Phosphate Dehydrogenase Deficiency" },
    answer: "B", explanation: "Lead poisoning (plumbism) from paint chips causes microcytic anemia with basophilic stippling." },
  { id: 44, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Hard",
    question: "What Blood Lead Level (BLL) threshold mandates initiation of oral chelation therapy with Succimer (DMSA) in an asymptomatic child?",
    options: { A: "≥ 5 µg/dL", B: "≥ 20 µg/dL", C: "≥ 45 µg/dL", D: "≥ 70 µg/dL" },
    answer: "C", explanation: "BLL ≥ 45 µg/dL mandates oral chelation therapy with Succimer (DMSA)." },
  { id: 45, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Medium",
    question: "Fanconi Anemia is a congenital constitutional aplastic anemia characterized by progressive bone marrow failure and physical malformations including:",
    options: { A: "Hypoplastic or absent thumbs and radial ray defects", B: "Polydactyly and syndactyly", C: "Macrocephaly and hypertelorism", D: "Congenital cataracts" },
    answer: "A", explanation: "Fanconi anemia features thumb/radial ray hypoplasia, hyperpigmentation, and pancytopenia." },
  { id: 46, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Medium",
    question: "Diamond-Blackfan Anemia (Congenital Pure Red-Cell Aplasia) presents in early infancy with severe anemia. Laboratory evaluation reveals:",
    options: { A: "Severe reticulocytopenia with normal platelet and leukocyte counts", B: "Severe pancytopenia with empty bone marrow", C: "Marked thrombocytosis and neutrophilia", D: "Intravascular hemolysis with hemoglobinuria" },
    answer: "A", explanation: "Diamond-Blackfan anemia presents with severe reticulocytopenia and isolated red cell aplasia." },
  { id: 47, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Easy",
    question: "An 8-month-old infant exclusively fed unfortified goat's milk presents with weakness, glossitis, and failure to thrive. Complete Blood Count reveals MCV 108 fL (macrocytic). What is the underlying cause?",
    options: { A: "Iron deficiency", B: "Folate deficiency", C: "Vitamin B12 deficiency", D: "Vitamin Pyridoxine deficiency" },
    answer: "B", explanation: "Unfortified goat's milk is deficient in folate, leading to macrocytic megaloblastic anemia." },
  { id: 48, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Medium",
    question: "Neurological manifestations (such as paresthesias, sensory ataxia, and subacute combined degeneration) distinguish which cause of megaloblastic anemia?",
    options: { A: "Folate deficiency", B: "Vitamin B12 (Cobalamin) deficiency", C: "Iron deficiency", D: "Vitamin C deficiency" },
    answer: "B", explanation: "Neurological deficits (subacute combined degeneration) are unique to Vitamin B12 deficiency." },
  { id: 49, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Medium",
    question: "Physiological anemia of infancy reaches its lowest hemoglobin level (nadir of 9.5–11.0 g/dL) at what age in a healthy full-term infant?",
    options: { A: "2 to 3 weeks", B: "8 to 12 weeks (2–3 months)", C: "6 months", D: "12 months" },
    answer: "B", explanation: "Physiological anemia nadir occurs at 8 to 12 weeks (2–3 months) in full-term infants." },
  { id: 50, topic: "Anemia", source: "Anemia Integrated.pdf", difficulty: "Medium",
    question: "In differentiating Iron Deficiency Anemia from Beta-Thalassemia Trait, Mentzer Index (MCV / RBC count) is calculated. A Mentzer Index LESS THAN 13 suggests:",
    options: { A: "Iron Deficiency Anemia", B: "Beta-Thalassemia Trait", C: "Folate deficiency", D: "Lead poisoning" },
    answer: "B", explanation: "Mentzer Index (MCV / RBC) < 13 strongly suggests Beta-Thalassemia Trait over iron deficiency." },

  { id: 51, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "Hereditary Spherocytosis is caused by a genetic defect in red blood cell membrane skeletal proteins, most commonly involving:",
    options: { A: "Spectrin and Ankyrin", B: "Hemoglobin beta chain", C: "Pyruvate kinase enzyme", D: "Glucose-6-phosphate dehydrogenase" },
    answer: "A", explanation: "Hereditary Spherocytosis stems from defects in membrane skeletal proteins Spectrin and Ankyrin." },
  { id: 52, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "A 5-year-old child with Hereditary Spherocytosis develops sudden severe fatigue, pallor, and drop in hemoglobin to 3 g/dL with reticulocyte count 0.1%. What infectious agent is the classic cause of this aplastic crisis?",
    options: { A: "Parvovirus B19", B: "Epstein-Barr Virus", C: "Cytomegalovirus", D: "Hepatitis A Virus" },
    answer: "A", explanation: "Parvovirus B19 infects erythroid precursors, triggering acute aplastic crisis in spherocytosis." },
  { id: 53, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "Which laboratory test demonstrates increased red cell lysis in hypotonic saline solutions, serving as a classic diagnostic test for Hereditary Spherocytosis?",
    options: { A: "Osmotic Fragility Test", B: "Direct Antiglobulin (Coombs) Test", C: "Hemoglobin Electrophoresis", D: "Sickle solubility test" },
    answer: "A", explanation: "Increased RBC lysis in hypotonic saline defines the Osmotic Fragility Test for spherocytosis." },
  { id: 54, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "Glucose-6-Phosphate Dehydrogenase (G6PD) deficiency is inherited as an:",
    options: { A: "Autosomal dominant trait", B: "Autosomal recessive trait", C: "X-linked recessive trait", D: "Mitochondrial trait" },
    answer: "C", explanation: "G6PD deficiency is an X-linked recessive enzymatic disorder." },
  { id: 55, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "A 4-year-old boy presents with dark tea-colored urine, jaundice, and hemoglobinuria 24 hours after eating fava beans. Stained blood smear demonstrates Heinz bodies. Heinz bodies represent:",
    options: { A: "Precipitated denatured hemoglobin due to oxidative stress", B: "Nuclear remnants in reticulocytes", C: "Iron granules inside sideroblasts", D: "Parasitic inclusions" },
    answer: "A", explanation: "Heinz bodies represent oxidized denatured hemoglobin precipitates inside RBCs." },
  { id: 56, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Hard",
    question: "To avoid false-negative results, direct measurement of G6PD enzyme activity should be performed at what time relative to an acute hemolytic episode?",
    options: { A: "Immediately during the acute hemolytic crisis", B: "2 to 3 weeks AFTER resolution of the hemolytic episode", C: "During peak hemoglobinuria", D: "Immediately following blood transfusion" },
    answer: "B", explanation: "G6PD assay should be measured 2–3 weeks after crisis to avoid false negatives in young RBCs." },
  { id: 57, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "Sickle Cell Disease is caused by a point mutation in the beta-globin gene substituting valine for glutamic acid at position 6. Oxygen deprivation causes HbS polymerization resulting in:",
    options: { A: "Rigid sickle-shaped RBCs and microvascular occlusion", B: "Spherocyte formation", C: "Target cell destruction in liver", D: "Immediate osmotic lysis" },
    answer: "A", explanation: "HbS polymerization under hypoxia creates rigid sickle RBCs causing vaso-occlusion." },
  { id: 58, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Easy",
    question: "Painful swelling of the hands and feet (Dactylitis or hand-foot syndrome) is the classic initial vaso-occlusive manifestation of Sickle Cell Disease in infants aged:",
    options: { A: "6 months to 2 years", B: "6 to 9 years", C: "12 to 15 years", D: "> 18 years" },
    answer: "A", explanation: "Dactylitis (hand-foot syndrome) is the earliest vaso-occlusive sign in infants 6m–2y." },
  { id: 59, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Medium",
    question: "Beta-Thalassemia Major is characterized by absent or severely reduced beta-globin synthesis. Hemoglobin electrophoresis in an untreated child shows:",
    options: { A: "Marked elevation of HbF (30% to 90%) with absent or minimal HbA", B: "100% Normal HbA", C: "Elevated HbS (80%)", D: "Isolated elevation of HbA2 to 90%" },
    answer: "A", explanation: "Beta-Thalassemia Major exhibits marked elevation of HbF (30%–90%) on electrophoresis." },
  { id: 60, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Medium",
    question: "Iron chelation therapy with Deferoxamine or Deferasirox is initiated in chronically transfused thalassemic children to prevent fatal organ damage to the:",
    options: { A: "Heart (transfusional iron overload cardiomyopathy)", B: "Spleen", C: "Lungs", D: "Thyroid gland alone" },
    answer: "A", explanation: "Iron chelation prevents transfusional iron deposition in the heart (cardiomyopathy)." },

  { id: 61, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Easy",
    question: "Upper gastrointestinal bleeding is defined as bleeding originating proximal to the:",
    options: { A: "Pyloric sphincter", B: "Ligament of Treitz (duodenojejunal junction)", C: "Ileocecal valve", D: "Splenic flexure" },
    answer: "B", explanation: "Upper GI bleeding originates proximal to the Ligament of Treitz." },
  { id: 62, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Medium",
    question: "A 2-day-old neonate vomits dark blood. To distinguish swallowed maternal blood from active neonatal GI bleeding, the Apt-Downey test is performed. Fetal hemoglobin (HbF) is identified because it is:",
    options: { A: "Resistant to alkali denaturation (remains pink)", B: "Destroyed by alkali denaturation (turns yellow-brown)", C: "Precipitated by alcohol", D: "Labeled by Coombs reagent" },
    answer: "A", explanation: "Fetal hemoglobin (HbF) is alkali-resistant, remaining pink in the Apt-Downey test." },
  { id: 63, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Hard",
    question: "In evaluating a child with upper GI bleeding, a Sheffield Pediatric GI Bleeding Score greater than what threshold indicates urgent endoscopy?",
    options: { A: "Score > 2", B: "Score > 5", C: "Score > 8", D: "Score > 15" },
    answer: "C", explanation: "Sheffield GI Bleeding Score > 8 indicates severe hemorrhage requiring urgent endoscopy." },
  { id: 64, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Easy",
    question: "Painless, massive, dark red (maroon) lower GI bleeding in a 15-month-old child is the classic presentation of:",
    options: { A: "Meckel's Diverticulum", B: "Anal fissure", C: "Intussusception", D: "Ulcerative colitis" },
    answer: "A", explanation: "Painless, massive maroon rectal bleeding in a toddler is classic for Meckel's Diverticulum." },
  { id: 65, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Easy",
    question: "An 18-month-old infant presents with sudden onset of severe intermittent abdominal pain every 15 to 20 minutes, drawing up of knees, bilious vomiting, and passage of 'currant jelly' stool. Abdominal exam reveals a sausage-shaped mass in the right upper quadrant. What is the diagnosis?",
    options: { A: "Hypertrophic pyloric stenosis", B: "Acute Intussusception", C: "Hirschsprung disease", D: "Duodenal atresia" },
    answer: "B", explanation: "Intermittent colic, knees drawn up, currant jelly stool, and sausage mass = Intussusception." },
  { id: 66, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Medium",
    question: "What non-surgical intervention is both diagnostic and therapeutic for non-strangulated acute intussusception in children?",
    options: { A: "Air or hydrostatic (saline/barium) contrast enema reduction", B: "High-dose oral osmotic laxatives", C: "Endoscopic band ligation", D: "Intravenous Octreotide infusion" },
    answer: "A", explanation: "Air or hydrostatic (saline/barium) contrast enema is diagnostic and therapeutic for intussusception." },
  { id: 67, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Medium",
    question: "In a child presenting with upper GI bleeding due to rupture of esophageal varices secondary to portal hypertension, which vasoactive drug is administered IV to reduce portal venous pressure?",
    options: { A: "Terlipressin or Octreotide", B: "Dopamine", C: "Furosemide", D: "Atropine" },
    answer: "A", explanation: "Terlipressin or Octreotide infusion reduces splanchnic blood flow in variceal bleeding." },

  { id: 68, topic: "GIT", source: "GIT integrated lecture - Copy.pdf", difficulty: "Easy",
    question: "Hirschsprung Disease (congenital aganglionic megacolon) is characterized by the absence of parasympathetic ganglion cells in which intestinal nervous plexuses?",
    options: { A: "Submucosal (Meissner) and myenteric (Auerbach) plexuses", B: "Celiac plexus alone", C: "Vagus nerve trunk", D: "Sympathetic chain ganglia" },
    answer: "A", explanation: "Hirschsprung Disease lacks parasympathetic ganglion cells in Meissner and Auerbach plexuses." },
  { id: 69, topic: "GIT", source: "GIT integrated lecture - Copy.pdf", difficulty: "Easy",
    question: "A newborn fails to pass meconium within the first 48 hours of life and develops abdominal distension and bilious vomiting. Digital rectal exam reveals a tight anal sphincter followed by an explosive release of gas and liquid stool upon finger withdrawal ('squirt sign'). What is the diagnosis?",
    options: { A: "Imperforate anus", B: "Hirschsprung Disease", C: "Meconium ileus", D: "Functional constipation" },
    answer: "B", explanation: "Delayed meconium (>48h), distension, and squirt sign on DRE indicate Hirschsprung Disease." },
  { id: 70, topic: "GIT", source: "GIT integrated lecture - Copy.pdf", difficulty: "Easy",
    question: "What is the definitive gold-standard diagnostic procedure to confirm Hirschsprung Disease?",
    options: { A: "Suction rectal biopsy demonstrating absence of ganglion cells", B: "Abdominal plain X-ray", C: "Stool culture", D: "Serum gastrin level" },
    answer: "A", explanation: "Suction rectal biopsy demonstrating absence of ganglion cells is the gold standard diagnosis." },

  { id: 71, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "Nutritional rickets is defined as a disease of the growing skeleton caused by defective mineralization of osteoid matrix and growth plate cartilage due to deficiency of:",
    options: { A: "Vitamin D and/or Calcium", B: "Vitamin C", C: "Vitamin K", D: "Iron" },
    answer: "A", explanation: "Rickets is caused by defective bone and cartilage mineralization due to Vitamin D/Ca deficiency." },
  { id: 72, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "What is the EARLIEST cranial physical sign of active rickets seen in infants under 6 months of age?",
    options: { A: "Frontal bossing", B: "Craniotabes (ping-pong ball softness of parietal bones)", C: "Delayed fontanel closure", D: "High arched palate" },
    answer: "B", explanation: "Craniotabes (soft ping-pong skull) is the earliest cranial physical sign in infants under 6 months." },
  { id: 73, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "Palpable, visible bead-like enlargement of the costochondral junctions along the anterolateral chest wall in rickets is known as:",
    options: { A: "Harrison's sulcus", B: "Rachitic Rosary", C: "Pigeon chest (Pectus carinatum)", D: "Funnel chest" },
    answer: "B", explanation: "Palpable enlargement of costochondral junctions creates the Rachitic Rosary." },
  { id: 74, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "Which biochemical serum marker is the MOST SENSITIVE indicator of active rickets, remaining elevated even when serum calcium is normal?",
    options: { A: "Serum total calcium", B: "Serum inorganic phosphorus", C: "Serum Alkaline Phosphatase (ALP)", D: "25-hydroxyvitamin D" },
    answer: "C", explanation: "Serum Alkaline Phosphatase (ALP) is the most sensitive marker of active rickets." },
  { id: 75, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "Characteristic radiological changes of active rickets seen on plain wrist X-rays include:",
    options: { A: "Metaphyseal cupping, fraying, and splaying with widened epiphyseal growth plate", B: "Subperiosteal hematoma and dense Frankel lines", C: "Cortical bone thickening without widening", D: "Osteopetrosis and rugger-jersey spine" },
    answer: "A", explanation: "Wrist X-ray in active rickets shows metaphyseal cupping, fraying, and splaying." },
  { id: 76, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Medium",
    question: "Stoss therapy for active nutritional rickets involves single oral administration of high-dose Vitamin D (Cholecalciferol) at what dosage?",
    options: { A: "1,000 to 2,000 IU", B: "10,000 to 20,000 IU", C: "300,000 to 600,000 IU", D: "2,000,000 IU" },
    answer: "C", explanation: "Stoss therapy consists of a single high dose of 300,000 to 600,000 IU Vitamin D." },
  { id: 77, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Hard",
    question: "Vitamin D-Dependent Rickets Type 1 (VDDR-1) is caused by an inactivating mutation in the CYP27B1 gene encoding which enzyme?",
    options: { A: "25-hydroxylase in liver", B: "1-alpha-hydroxylase in kidneys", C: "24-hydroxylase", D: "Alkaline phosphatase" },
    answer: "B", explanation: "VDDR-1 is caused by 1-alpha-hydroxylase gene (CYP27B1) inactivating mutation in kidneys." },
  { id: 78, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Hard",
    question: "Vitamin D-Dependent Rickets Type 2 (VDDR-2) differs from Type 1 by presenting with severe resistance to 1,25(OH)2D3 and frequent association with:",
    options: { A: "Total Alopecia (hair loss)", B: "Congenital deafness", C: "Hepatic cirrhosis", D: "Cataracts" },
    answer: "A", explanation: "VDDR-2 involves Vitamin D Receptor (VDR) resistance and frequently presents with total alopecia." },
  { id: 79, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Hard",
    question: "X-linked Hypophosphatemic Rickets (Vitamin D-Resistant Rickets) is caused by mutations in the PHEX gene leading to elevated levels of which renal phosphate-wasting hormone?",
    options: { A: "Parathyroid Hormone (PTH)", B: "Fibroblast Growth Factor 23 (FGF-23)", C: "Calcitonin", D: "Renin" },
    answer: "B", explanation: "X-linked hypophosphatemic rickets involves PHEX mutation causing elevated FGF-23 levels." },
  { id: 80, topic: "Rickets", source: "Rickets (undergraduates).pdf", difficulty: "Easy",
    question: "What is the recommended daily oral Vitamin D prophylactic dose for all breastfed infants from birth until 12 months of age?",
    options: { A: "100 IU/day", B: "400 IU/day", C: "1,000 IU/day", D: "5,000 IU/day" },
    answer: "B", explanation: "Daily Vitamin D prophylaxis for breastfed infants up to 12 months is 400 IU/day." },

  { id: 81, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Primary hemostasis involves vascular constriction and formation of an unstable platelet plug. Clinical manifestations of primary hemostatic defects include:",
    options: { A: "Petechiae, purpura, and mucosal bleeding (epistaxis, gum bleeding)", B: "Deep muscle hematomas and hemarthrosis (joint bleeding)", C: "Delayed retroperitoneal bleeding", D: "Isolated hemoperitoneum" },
    answer: "A", explanation: "Primary hemostatic defects present with superficial skin petechiae, purpura, and mucosal bleeding." },
  { id: 82, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Secondary hemostasis involves activation of the coagulation cascade to form a stable fibrin clot. Defects in secondary hemostasis (such as Hemophilia) typically present with:",
    options: { A: "Immediate petechiae and superficial purpura", B: "Deep tissue hematomas and hemarthrosis", C: "Prolonged bleeding time with normal aPTT", D: "Isolated splenomegaly" },
    answer: "B", explanation: "Secondary hemostatic defects present with deep tissue hematomas and hemarthrosis." },
  { id: 83, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Activated Partial Thromboplastin Time (aPTT) evaluates which pathways of the coagulation cascade?",
    options: { A: "Extrinsic pathway only (Factor VII)", B: "Intrinsic pathway (Factors VIII, IX, XI, XII) and Common pathway", C: "Platelet aggregation", D: "Fibrinolysis only" },
    answer: "B", explanation: "aPTT evaluates the intrinsic pathway (Factors VIII, IX, XI, XII) and common pathway." },
  { id: 84, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Prothrombin Time (PT / INR) specifically evaluates which unique factor in the extrinsic coagulation pathway?",
    options: { A: "Factor VII", B: "Factor VIII", C: "Factor IX", D: "Factor XII" },
    answer: "A", explanation: "Prothrombin Time (PT) specifically evaluates Factor VII in the extrinsic pathway." },
  { id: 85, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Medium",
    question: "A 2-year-old boy presents with hemarthrosis of the right knee after minor trauma. Laboratory evaluation shows: PT normal, aPTT 75 seconds (prolonged). A 1:1 mixing study with normal control plasma CORRECTS the aPTT to normal. What does this mixing study result indicate?",
    options: { A: "Coagulation factor deficiency (e.g., Factor VIII or IX deficiency)", B: "Presence of a specific factor inhibitor (antibody)", C: "Lupus anticoagulant", D: "Severe thrombocytopenia" },
    answer: "A", explanation: "Correction of aPTT on a 1:1 mixing study confirms a coagulation factor deficiency." },
  { id: 86, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Severe Hemophilia A or B is defined by a specific clotting factor level (Factor VIII or IX) of:",
    options: { A: "Less than 1% (< 0.01 IU/mL)", B: "1% to 5%", C: "5% to 40%", D: "50% to 100%" },
    answer: "A", explanation: "Severe Hemophilia is defined as clotting factor activity < 1% (< 0.01 IU/mL)." },
  { id: 87, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "What is the inheritance pattern of Hemophilia A (Factor VIII deficiency) and Hemophilia B (Factor IX deficiency)?",
    options: { A: "Autosomal dominant", B: "Autosomal recessive", C: "X-linked recessive", D: "Mitochondrial" },
    answer: "C", explanation: "Hemophilia A and B are inherited in an X-linked recessive pattern." },
  { id: 88, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Hard",
    question: "To raise plasma Factor VIII level by 100% in a hemophilic child with life-threatening intracranial hemorrhage, how many units/kg of recombinant Factor VIII concentrate should be infused?",
    options: { A: "10 IU/kg", B: "25 IU/kg", C: "50 IU/kg", D: "100 IU/kg" },
    answer: "C", explanation: "1 IU/kg Factor VIII raises plasma level by 2%; 50 IU/kg raises level by 100%." },
  { id: 89, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Medium",
    question: "Desmopressin (DDAVP) is effective in controlling mild bleeding episodes in patients with Mild Hemophilia A because it releases endogenous Factor VIII and von Willebrand factor from:",
    options: { A: "Splenic macrophages", B: "Vascular endothelial storage sites (Weibel-Palade bodies)", C: "Bone marrow megakaryocytes", D: "Hepato-biliary sinusoids" },
    answer: "B", explanation: "DDAVP triggers endothelial release of vWF and Factor VIII from Weibel-Palade bodies." },
  { id: 90, topic: "Hemorrhagic Disorders", source: "Hemorrhagic disorders integ. 2026.pdf", difficulty: "Easy",
    question: "Von Willebrand Disease (vWD) is the most common inherited bleeding disorder. Von Willebrand Factor functions in hemostasis by promoting:",
    options: { A: "Platelet adhesion to subendothelial collagen and carrying/stabilizing Factor VIII in plasma", B: "Direct activation of Prothrombin to Thrombin", C: "Fibrinolysis of old clots", D: "Inhibition of Protein C" },
    answer: "A", explanation: "vWF mediates platelet adhesion to collagen and acts as a carrier protein for Factor VIII." },

  { id: 91, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Easy",
    question: "What is the normal circulating platelet count range in children?",
    options: { A: "50,000 to 100,000 /mm³", B: "150,000 to 450,000 /mm³", C: "500,000 to 800,000 /mm³", D: "1,000,000 /mm³" },
    answer: "B", explanation: "Normal circulating platelet count ranges between 150,000 and 450,000 /mm³." },
  { id: 92, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Easy",
    question: "A previously healthy 3-year-old child presents with sudden onset generalized petechiae, purpura, and epistaxis 2 weeks following a viral upper respiratory infection. CBC reveals isolated severe thrombocytopenia (platelets 12,000/mm³) with normal hemoglobin and WBC count. What is the diagnosis?",
    options: { A: "Acute Immune Thrombocytopenic Purpura (ITP)", B: "Acute Lymphoblastic Leukemia", C: "Aplastic Anemia", D: "Henoch-Schönlein Purpura" },
    answer: "A", explanation: "Acute ITP presents post-viral with sudden isolated severe thrombocytopenia." },
  { id: 93, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Easy",
    question: "In acute ITP, anti-platelet autoantibodies (typically IgG) coat circulating platelets, leading to their destruction by macrophages primarily located in the:",
    options: { A: "Liver", B: "Spleen", C: "Bone marrow", D: "Lymph nodes" },
    answer: "B", explanation: "Antibody-coated platelets are cleared by Fc macrophages in the spleen." },
  { id: 94, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Easy",
    question: "Spontaneous complete recovery occurs within 6 months without long-term sequelae in what percentage of children with acute ITP?",
    options: { A: "20%", B: "50%", C: "80%", D: "99%" },
    answer: "C", explanation: "80% of pediatric acute ITP cases achieve spontaneous complete recovery within 6 months." },
  { id: 95, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Medium",
    question: "What first-line pharmacologic treatment for pediatric ITP rapidly blocks splenic macrophage Fc receptors, leading to a swift rise in platelet count within 24 to 48 hours?",
    options: { A: "Intravenous Immunoglobulin (IVIG)", B: "Oral Aspirin", C: "Recombinant Factor VIIa", D: "Oral Methotrexate" },
    answer: "A", explanation: "IVIG rapidly saturates and blocks macrophage Fc receptors in the spleen." },
  { id: 96, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Medium",
    question: "Glanzmann Thrombasthenia is a congenital qualitative platelet defect caused by deficiency or dysfunction of:",
    options: { A: "Glycoprotein Ib/IX complex (vWF receptor)", B: "Glycoprotein IIb/IIIa complex (Fibrinogen receptor)", C: "Factor V", D: "Thromboxane A2" },
    answer: "B", explanation: "Glanzmann Thrombasthenia is caused by GPIIb/IIIa complex (fibrinogen receptor) dysfunction." },
  { id: 97, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Medium",
    question: "Bernard-Soulier Syndrome is characterized by thrombocytopenia, giant platelets on peripheral smear, and defective platelet adhesion due to deficiency of:",
    options: { A: "Glycoprotein Ib/IX complex", B: "Glycoprotein IIb/IIIa complex", C: "Factor VIII", D: "Protein C" },
    answer: "A", explanation: "Bernard-Soulier Syndrome is caused by GPIb/IX complex deficiency (giant platelets)." },
  { id: 98, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Easy",
    question: "A 5-year-old child presents with non-thrombocytopenic palpable purpura over the buttocks and lower extremities, colicky abdominal pain, non-deforming joint arthralgias, and microscopic hematuria. Platelet count is completely NORMAL (280,000/mm³). What is the diagnosis?",
    options: { A: "Immune Thrombocytopenic Purpura", B: "Henoch-Schönlein Purpura (HSP / IgA Vasculitis)", C: "Hemophilia A", D: "Meningococcemia" },
    answer: "B", explanation: "Non-thrombocytopenic palpable purpura, joint pain, abdominal colic, and hematuria = HSP." },
  { id: 99, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Medium",
    question: "What underlying histopathological lesion characterizes Henoch-Schönlein Purpura (HSP)?",
    options: { A: "IgA immune complex leukocytoclastic vasculitis of small blood vessels", B: "Platelet microthrombi in large arteries", C: "Granulomatous inflammation of large vessels", D: "Venous stasis thrombosis" },
    answer: "A", explanation: "HSP is driven by IgA immune complex leukocytoclastic vasculitis of small arterioles." },
  { id: 100, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Advanced",
    question: "Wiskott-Aldrich Syndrome is an X-linked immunodeficiency disorder characterized by the clinical triad of:",
    options: { A: "Microthrombocytopenia (small platelets), eczema, and recurrent immunodeficiency infections", B: "Thrombocytopenia, absent radii, and cardiac septal defects", C: "Purpura, arthritis, and glomerulonephritis", D: "Anemia, splenomegaly, and gallstones" },
    answer: "A", explanation: "Wiskott-Aldrich Syndrome triad: microthrombocytopenia, eczema, and immunodeficiency." },

  { id: 101, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "What is the most common childhood cancer, representing approximately 31% of all pediatric malignancies?",
    options: { A: "Brain tumors", B: "Leukemia", C: "Neuroblastoma", D: "Wilms tumor" },
    answer: "B", explanation: "Leukemia is the most common childhood cancer (~31% of all pediatric malignancies)." },
  { id: 102, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Acute Lymphoblastic Leukemia (ALL) accounts for what percentage of all childhood leukemias?",
    options: { A: "15%", B: "35%", C: "77% (approx. 3/4 of cases)", D: "95%" },
    answer: "C", explanation: "ALL accounts for ~77% (approx. 3/4) of all childhood leukemias." },
  { id: 103, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "What is the peak age incidence for Acute Lymphoblastic Leukemia (ALL) in children?",
    options: { A: "Under 6 months", B: "2 to 3 years of age", C: "8 to 10 years of age", D: "14 to 16 years of age" },
    answer: "B", explanation: "ALL incidence peaks between 2 and 3 years of age." },
  { id: 104, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Which genetic syndrome carries a 10- to 20-fold increased risk of developing Acute Lymphoblastic Leukemia (ALL)?",
    options: { A: "Down Syndrome (Trisomy 21)", B: "Turner Syndrome", C: "Marfan Syndrome", D: "Achondroplasia" },
    answer: "A", explanation: "Down Syndrome (Trisomy 21) carries a 10- to 20-fold increased risk of developing ALL." },
  { id: 105, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Definitive diagnosis of ALL requires bone marrow examination showing what minimum threshold of lymphoblasts?",
    options: { A: "> 5%", B: "> 10%", C: "≥ 25% lymphoblasts", D: "> 50%" },
    answer: "C", explanation: "Bone marrow aspirate showing ≥ 25% lymphoblasts is diagnostic for ALL." },
  { id: 106, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "A 4-year-old child diagnosed with ALL initiates induction chemotherapy. 48 hours later, lab results demonstrate hyperuricemia, hyperkalemia, hyperphosphatemia, and secondary hypocalcemia. What is this life-threatening oncologic emergency called?",
    options: { A: "Acute Tumor Lysis Syndrome (TLS)", B: "Refeeding Syndrome", C: "Graft-versus-host disease", D: "Disseminated intravascular coagulation" },
    answer: "A", explanation: "Rapid tumor breakdown causes Tumor Lysis Syndrome (hyperuricemia, hyperK, hyperP, hypoCa)." },
  { id: 107, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Medium",
    question: "Standard 4-week multiagent induction chemotherapy for pediatric ALL combines which three drugs?",
    options: { A: "Vincristine, Corticosteroid (Prednisone/Dexamethasone), and L-Asparaginase", B: "Cisplatin, Doxorubicin, and Cyclophosphamide", C: "Methotrexate, Fluorouracil, and Cytarabine", D: "Bleomycin, Etoposide, and Cisplatin" },
    answer: "A", explanation: "ALL induction chemo combines Vincristine, Corticosteroid, and L-Asparaginase." },
  { id: 108, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Pathognomonic Reed-Sternberg cells (multinucleated giant cells with 'owl-eye' nucleoli) on lymph node biopsy are diagnostic for:",
    options: { A: "Non-Hodgkin Lymphoma", B: "Hodgkin Lymphoma", C: "Acute Lymphoblastic Leukemia", D: "Neuroblastoma" },
    answer: "B", explanation: "Reed-Sternberg cells (owl-eye nucleoli) pathognomonically define Hodgkin Lymphoma." },
  { id: 109, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Biopsy of Burkitt Lymphoma (an aggressive B-cell Non-Hodgkin Lymphoma linked to Epstein-Barr Virus) classically shows which histological appearance?",
    options: { A: "'Starry-sky' pattern (macrophages ingesting debris amidst dark lymphoblasts)", B: "'Hair-on-end' pattern", C: "Homer-Wright rosettes", D: "Psammoma bodies" },
    answer: "A", explanation: "Burkitt Lymphoma displays a characteristic 'starry-sky' histological appearance." },
  { id: 110, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Neuroblastoma originates from embryonic neural crest cells. Urinary excretion of which catecholamine metabolites is elevated in over 90% of neuroblastoma cases?",
    options: { A: "Vanillylmandelic Acid (VMA) and Homovanillic Acid (HVA)", B: "5-HIAA", C: "Serum serotonin", D: "Cortisol" },
    answer: "A", explanation: "Elevated urinary VMA and HVA occur in over 90% of neuroblastoma cases." },
  { id: 111, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Medium",
    question: "A 2-year-old child presents with periorbital ecchymosis ('raccoon eyes'), proptosis, and a hard abdominal mass that CROSSES the midline. What is the diagnosis?",
    options: { A: "Wilms tumor (Nephroblastoma)", B: "Metastatic Neuroblastoma", C: "Hepatoblastoma", D: "Renal cell carcinoma" },
    answer: "B", explanation: "Metastatic Neuroblastoma presents with raccoon eyes, proptosis, and a mass crossing midline." },
  { id: 112, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Medium",
    question: "A 3-year-old child is found to have a smooth, firm, painless flank mass on one side during bathing. The mass does NOT cross the midline. Urinalysis reveals microscopic hematuria. Gentle palpation is emphasized during exam to avoid:",
    options: { A: "Rupture of Wilms Tumor capsule and peritoneal tumor seeding", B: "Acute splenic infarction", C: "Sudden hypertensive crisis", D: "Intestinal perforation" },
    answer: "A", explanation: "Palpating Wilms tumor must be gentle to avoid capsule rupture and peritoneal seeding." },
  { id: 113, topic: "Oncology", source: "oncology - final.pdf", difficulty: "Easy",
    question: "Overall 5-year survival rate for pediatric ALL treated under modern risk-adapted chemotherapy protocols exceeds:",
    options: { A: "30%", B: "50%", C: "85%", D: "100%" },
    answer: "C", explanation: "Modern risk-adapted ALL therapy achieves > 85% 5-year overall survival." },

  { id: 114, topic: "GIT", source: "GIT integrated lecture - Copy.pdf", difficulty: "Easy",
    question: "Pediatric functional constipation under Rome IV criteria is defined as bowel movements occurring less than how many times per week?",
    options: { A: "2 or fewer times per week", B: "4 times per week", C: "6 times per week", D: "Once every 3 weeks" },
    answer: "A", explanation: "Functional constipation under Rome IV criteria requires ≤ 2 bowel movements per week." },
  { id: 115, topic: "GIT", source: "GIT integrated lecture - Copy.pdf", difficulty: "Easy",
    question: "First-line medical maintenance therapy for functional constipation in infants and children includes which osmotic laxative?",
    options: { A: "Polyethylene Glycol (PEG 3350) or Lactulose", B: "Senna and Castor oil", C: "Bisacodyl suppositories daily", D: "Mineral oil in neonates" },
    answer: "A", explanation: "Polyethylene Glycol (PEG 3350) or Lactulose is first-line maintenance laxative." },
  { id: 116, topic: "GI Bleeding", source: "GIT bleeding.pdf", difficulty: "Medium",
    question: "In an infant presenting with acute lower GI bleeding, milk-protein induced allergic proctocolitis is managed by:",
    options: { A: "Surgical bowel resection", B: "Eliminating cow's milk protein from maternal diet (if breastfed) or switching to extensively hydrolyzed formula", C: "Oral Vancomycin therapy", D: "Immediate blood transfusion" },
    answer: "B", explanation: "Allergic proctocolitis is managed by eliminating dairy from maternal diet or using hydrolyzed formula." },
  { id: 117, topic: "Acute Malnutrition", source: "Acute Malnutrition in Children.pdf", difficulty: "Hard",
    question: "What is the recommended oral rehydration rate of ReSoMal during the initial 2 hours of treating dehydration in a child with SAM?",
    options: { A: "5 mL/kg every 30 minutes for 2 hours", B: "20 mL/kg rapid IV bolus", C: "50 mL/kg every hour", D: "100 mL/kg over 24 hours" },
    answer: "A", explanation: "ReSoMal is administered at 5 mL/kg every 30 minutes for the initial 2 hours in SAM." },
  { id: 118, topic: "Hemolytic Anemia", source: "Hemolytic Anemia 4th year (2).pdf", difficulty: "Advanced",
    question: "In Beta-Thalassemia Trait (minor), Hb A2 levels on hemoglobin electrophoresis are characteristically:",
    options: { A: "Elevated > 3.5%", B: "Normal or < 1%", C: "Completely absent", D: "100%" },
    answer: "A", explanation: "Hb A2 is characteristically elevated > 3.5% in Beta-Thalassemia Trait." },
  { id: 119, topic: "Platelet Disorders", source: "Platelet Disorders.pdf", difficulty: "Hard",
    question: "Intracranial hemorrhage in an infant with acute ITP is a life-threatening emergency. Immediate emergency medical therapy consists of:",
    options: { A: "High-dose IV Methylprednisolone + IVIG + Platelet transfusion", B: "Oral Aspirin + Heparin", C: "Observation alone", D: "Oral Ferrous sulfate" },
    answer: "A", explanation: "Emergency medical therapy for ITP bleeding: pulse IV Methylprednisolone + IVIG + platelets." },
  { id: 120, topic: "Acute Diarrhea", source: "Acute diarrhea.pdf", difficulty: "Advanced",
    question: "A child with acute diarrhea, anemia, thrombocytopenia, and elevated BUN/creatinine following a dysenteric illness presents the classic clinical triad of:",
    options: { A: "Hemolytic Uremic Syndrome (HUS)", B: "Henoch-Schönlein Purpura", C: "Disseminated Intravascular Coagulation", D: "Refeeding Syndrome" },
    answer: "A", explanation: "Anemia, thrombocytopenia, and elevated renal function following dysentery = HUS." }
];

// Allows use in Node / bundlers without breaking plain <script> usage in the browser
if (typeof module !== "undefined" && module.exports) {
  module.exports = questionsData;
}
